In [6]:
import pandas as pd

df = pd.read_csv("cleaned_twitter_data.csv")

df.head()

,USER_ID,ENTITY,SENTIMENT,TEXT
0,2401,Borderlands,Positive,im getting on borderlands and i will murder yo...
1,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
2,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
3,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
4,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...

In [7]:
df.columns

Index(['USER_ID', 'ENTITY', 'SENTIMENT', 'TEXT'], dtype='str')

In [8]:
df.shape

(59118, 4)

**Step 1: Text Cleaning.**

In [9]:
df["TEXT"].head(10)

0    im getting on borderlands and i will murder yo...
1    I am coming to the borders and I will kill you...
2    im getting on borderlands and i will kill you ...
3    im coming on borderlands and i will murder you...
4    im getting on borderlands 2 and i will murder ...
5    im getting into borderlands and i can murder y...
6    So I spent a few hours making something for fu...
7    So I spent a couple of hours doing something f...
8    So I spent a few hours doing something for fun...
9    So I spent a few hours making something for fu...
Name: TEXT, dtype: str

In [10]:
import re

def clean_text(text):
    text = text.lower()                      # lowercase
    text = re.sub(r"http\S+|www\S+", "", text)  # remove URLs
    text = re.sub(r"@\w+", "", text)         # remove mentions
    text = re.sub(r"[^a-zA-Z\s]", "", text)  # remove special characters
    text = re.sub(r"\s+", " ", text).strip() # remove extra spaces
    
    return text

In [11]:
df["CLEAN_TEXT"] = df["TEXT"].apply(clean_text)

In [12]:
df[["TEXT", "CLEAN_TEXT"]].head(10)

,TEXT,CLEAN_TEXT
0,im getting on borderlands and i will murder yo...,im getting on borderlands and i will murder yo...
1,I am coming to the borders and I will kill you...,i am coming to the borders and i will kill you...
2,im getting on borderlands and i will kill you ...,im getting on borderlands and i will kill you all
3,im coming on borderlands and i will murder you...,im coming on borderlands and i will murder you...
4,im getting on borderlands 2 and i will murder ...,im getting on borderlands and i will murder yo...
5,im getting into borderlands and i can murder y...,im getting into borderlands and i can murder y...
6,So I spent a few hours making something for fu...,so i spent a few hours making something for fu...
7,So I spent a couple of hours doing something f...,so i spent a couple of hours doing something f...
8,So I spent a few hours doing something for fun...,so i spent a few hours doing something for fun...
9,So I spent a few hours making something for fu...,so i spent a few hours making something for fu...

**Step 2 — Tokenization.**

In [13]:
import nltk

In [14]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to C:\Users\MANISA
[nltk_data]     GHOSH\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\MANISA
[nltk_data]     GHOSH\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [15]:
from nltk.tokenize import word_tokenize

In [16]:
df["TOKENS"] = df["CLEAN_TEXT"].apply(word_tokenize)

In [17]:
df[["CLEAN_TEXT", "TOKENS"]].head()

,CLEAN_TEXT,TOKENS
0,im getting on borderlands and i will murder yo...,"[im, getting, on, borderlands, and, i, will, m..."
1,i am coming to the borders and i will kill you...,"[i, am, coming, to, the, borders, and, i, will..."
2,im getting on borderlands and i will kill you all,"[im, getting, on, borderlands, and, i, will, k..."
3,im coming on borderlands and i will murder you...,"[im, coming, on, borderlands, and, i, will, mu..."
4,im getting on borderlands and i will murder yo...,"[im, getting, on, borderlands, and, i, will, m..."

**Step 3 — Stopword Removal.**

In [18]:
from nltk.corpus import stopwords

nltk.download("stopwords")

[nltk_data] Downloading package stopwords to C:\Users\MANISA
[nltk_data]     GHOSH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
stop_words = set(stopwords.words("english")) - {"not", "no", "nor"}

In [20]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [21]:
df["NO_STOPWORDS"] = df["TOKENS"].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

In [22]:
df[["TOKENS", "NO_STOPWORDS"]].head()

,TOKENS,NO_STOPWORDS
0,"[im, getting, on, borderlands, and, i, will, m...","[im, getting, borderlands, murder]"
1,"[i, am, coming, to, the, borders, and, i, will...","[coming, borders, kill]"
2,"[im, getting, on, borderlands, and, i, will, k...","[im, getting, borderlands, kill]"
3,"[im, coming, on, borderlands, and, i, will, mu...","[im, coming, borderlands, murder]"
4,"[im, getting, on, borderlands, and, i, will, m...","[im, getting, borderlands, murder]"

**Step 4 — Stemming.**

In [23]:
from nltk.stem import PorterStemmer, SnowballStemmer

porter = PorterStemmer()
snowball = SnowballStemmer("english")

In [24]:
df["PORTER_STEMMED"] = df["NO_STOPWORDS"].apply(
    lambda tokens: [porter.stem(word) for word in tokens]
)

In [25]:
df["SNOWBALL_STEMMED"] = df["NO_STOPWORDS"].apply(
    lambda tokens: [snowball.stem(word) for word in tokens]
)

In [26]:
df[["NO_STOPWORDS", "PORTER_STEMMED", "SNOWBALL_STEMMED"]].head(10)

,NO_STOPWORDS,PORTER_STEMMED,SNOWBALL_STEMMED
0,"[im, getting, borderlands, murder]","[im, get, borderland, murder]","[im, get, borderland, murder]"
1,"[coming, borders, kill]","[come, border, kill]","[come, border, kill]"
2,"[im, getting, borderlands, kill]","[im, get, borderland, kill]","[im, get, borderland, kill]"
3,"[im, coming, borderlands, murder]","[im, come, borderland, murder]","[im, come, borderland, murder]"
4,"[im, getting, borderlands, murder]","[im, get, borderland, murder]","[im, get, borderland, murder]"
5,"[im, getting, borderlands, murder]","[im, get, borderland, murder]","[im, get, borderland, murder]"
6,"[spent, hours, making, something, fun, dont, k...","[spent, hour, make, someth, fun, dont, know, h...","[spent, hour, make, someth, fun, dont, know, h..."
7,"[spent, couple, hours, something, fun, dont, k...","[spent, coupl, hour, someth, fun, dont, know, ...","[spent, coupl, hour, someth, fun, dont, know, ..."
8,"[spent, hours, something, fun, dont, know, im,...","[spent, hour, someth, fun, dont, know, im, hug...","[spent, hour, someth, fun, dont, know, im, hug..."
9,"[spent, hours, making, something, fun, dont, k...","[spent, hour, make, someth, fun, dont, know, h...","[spent, hour, make, someth, fun, dont, know, h..."

In [27]:
df.columns

Index(['USER_ID', 'ENTITY', 'SENTIMENT', 'TEXT', 'CLEAN_TEXT', 'TOKENS',
       'NO_STOPWORDS', 'PORTER_STEMMED', 'SNOWBALL_STEMMED'],
      dtype='str')

In [28]:
df["PORTER_TEXT"] = df["PORTER_STEMMED"].apply(
    lambda tokens: " ".join(tokens)
)

df["SNOWBALL_TEXT"] = df["SNOWBALL_STEMMED"].apply(
    lambda tokens: " ".join(tokens)
)

In [29]:
df[["PORTER_TEXT", "SNOWBALL_TEXT"]].head()

                 PORTER_TEXT              SNOWBALL_TEXT
0   im get borderland murder   im get borderland murder
1           come border kill           come border kill
2     im get borderland kill     im get borderland kill
3  im come borderland murder  im come borderland murder
4   im get borderland murder   im get borderland murder

**Step 5 — Lemmatization.**

In [30]:
from nltk.stem import WordNetLemmatizer

nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to C:\Users\MANISA
[nltk_data]     GHOSH\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\MANISA
[nltk_data]     GHOSH\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [31]:
lemmatizer = WordNetLemmatizer()

In [32]:
df["LEMMATIZED"] = df["NO_STOPWORDS"].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

In [33]:
df[["NO_STOPWORDS", "LEMMATIZED"]].head(10)

,NO_STOPWORDS,LEMMATIZED
0,"[im, getting, borderlands, murder]","[im, getting, borderland, murder]"
1,"[coming, borders, kill]","[coming, border, kill]"
2,"[im, getting, borderlands, kill]","[im, getting, borderland, kill]"
3,"[im, coming, borderlands, murder]","[im, coming, borderland, murder]"
4,"[im, getting, borderlands, murder]","[im, getting, borderland, murder]"
5,"[im, getting, borderlands, murder]","[im, getting, borderland, murder]"
6,"[spent, hours, making, something, fun, dont, k...","[spent, hour, making, something, fun, dont, kn..."
7,"[spent, couple, hours, something, fun, dont, k...","[spent, couple, hour, something, fun, dont, kn..."
8,"[spent, hours, something, fun, dont, know, im,...","[spent, hour, something, fun, dont, know, im, ..."
9,"[spent, hours, making, something, fun, dont, k...","[spent, hour, making, something, fun, dont, kn..."

**Step 6 — N-grams**

In [34]:
from nltk.util import ngrams

In [35]:
def get_bigrams(tokens):
    return list(ngrams(tokens, 2))

In [36]:
df["BIGRAMS"] = df["NO_STOPWORDS"].apply(get_bigrams)

In [37]:
df[["NO_STOPWORDS", "BIGRAMS"]].head(10)

,NO_STOPWORDS,BIGRAMS
0,"[im, getting, borderlands, murder]","[(im, getting), (getting, borderlands), (borde..."
1,"[coming, borders, kill]","[(coming, borders), (borders, kill)]"
2,"[im, getting, borderlands, kill]","[(im, getting), (getting, borderlands), (borde..."
3,"[im, coming, borderlands, murder]","[(im, coming), (coming, borderlands), (borderl..."
4,"[im, getting, borderlands, murder]","[(im, getting), (getting, borderlands), (borde..."
5,"[im, getting, borderlands, murder]","[(im, getting), (getting, borderlands), (borde..."
6,"[spent, hours, making, something, fun, dont, k...","[(spent, hours), (hours, making), (making, som..."
7,"[spent, couple, hours, something, fun, dont, k...","[(spent, couple), (couple, hours), (hours, som..."
8,"[spent, hours, something, fun, dont, know, im,...","[(spent, hours), (hours, something), (somethin..."
9,"[spent, hours, making, something, fun, dont, k...","[(spent, hours), (hours, making), (making, som..."

**EXPERIMENT WHICH PREPROCESSING TO USE with TFIDF**

In [38]:
df["LEMMATIZED_TEXT"] = df["LEMMATIZED"].apply(
    lambda tokens: " ".join(tokens)
)

In [39]:
df[[
    "PORTER_TEXT",
    "SNOWBALL_TEXT",
    "LEMMATIZED_TEXT"
]].head(10)

,PORTER_TEXT,SNOWBALL_TEXT,LEMMATIZED_TEXT
0,im get borderland murder,im get borderland murder,im getting borderland murder
1,come border kill,come border kill,coming border kill
2,im get borderland kill,im get borderland kill,im getting borderland kill
3,im come borderland murder,im come borderland murder,im coming borderland murder
4,im get borderland murder,im get borderland murder,im getting borderland murder
5,im get borderland murder,im get borderland murder,im getting borderland murder
6,spent hour make someth fun dont know huge fan ...,spent hour make someth fun dont know huge fan ...,spent hour making something fun dont know huge...
7,spent coupl hour someth fun dont know im huge ...,spent coupl hour someth fun dont know im huge ...,spent couple hour something fun dont know im h...
8,spent hour someth fun dont know im huge border...,spent hour someth fun dont know im huge border...,spent hour something fun dont know im huge bor...
9,spent hour make someth fun dont know huge rhan...,spent hour make someth fun dont know huge rhan...,spent hour making something fun dont know huge...

In [40]:
X_porter = df["PORTER_TEXT"]
X_snowball = df["SNOWBALL_TEXT"]
X_lemmatized = df["LEMMATIZED_TEXT"]

y = df["SENTIMENT"]

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.index,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [42]:
porter_train = df.loc[X_train, "PORTER_TEXT"]
porter_test = df.loc[X_test, "PORTER_TEXT"]

In [43]:
snowball_train = df.loc[X_train, "SNOWBALL_TEXT"]
snowball_test = df.loc[X_test, "SNOWBALL_TEXT"]

In [44]:
lemmatized_train = df.loc[X_train, "LEMMATIZED_TEXT"]
lemmatized_test = df.loc[X_test, "LEMMATIZED_TEXT"]

In [45]:
df = df[df["PORTER_TEXT"].str.len() > 0]
df = df.drop_duplicates(subset="PORTER_TEXT")
df = df.reset_index(drop=True)

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [47]:
ngram_options = {
    "Unigram": (1, 1),
    "Bigram": (2, 2),
    "Unigram + Bigram": (1, 2),
    "Trigram": (3, 3),
    "Bigram + Trigram": (2, 3),
    "Unigram + Bigram + Trigram": (1, 3)
}

In [48]:
preprocessing_options = {
    "Porter": (porter_train, porter_test),
    "Snowball": (snowball_train, snowball_test),
    "Lemmatization": (lemmatized_train, lemmatized_test)
}

In [49]:
results = []

In [50]:
for preprocessing_name, (train_text, test_text) in preprocessing_options.items():

    for ngram_name, ngram_range in ngram_options.items():

        # TF-IDF
        tfidf = TfidfVectorizer(
            ngram_range=ngram_range
        )

        X_train_tfidf = tfidf.fit_transform(train_text)
        X_test_tfidf = tfidf.transform(test_text)

        # Logistic Regression
        model = LogisticRegression(max_iter=1000)

        model.fit(X_train_tfidf, y.loc[X_train])

        # Prediction
        y_pred = model.predict(X_test_tfidf)

        # Evaluation
        accuracy = accuracy_score(y.loc[X_test], y_pred)

        precision = precision_score(
            y.loc[X_test],
            y_pred,
            average="weighted"
        )

        recall = recall_score(
            y.loc[X_test],
            y_pred,
            average="weighted"
        )

        f1 = f1_score(
            y.loc[X_test],
            y_pred,
            average="weighted"
        )

        # Store results
        results.append({
            "Preprocessing": preprocessing_name,
            "N-gram": ngram_name,
            "Accuracy": accuracy,
            "Precision": precision,
            "Recall": recall,
            "F1-Score": f1
        })

In [51]:
results_df = pd.DataFrame(results)
results_df

,Preprocessing,N-gram,Accuracy,Precision,Recall,F1-Score
0,Porter,Unigram,0.786367,0.786234,0.786367,0.786230
1,Porter,Bigram,0.890477,0.898818,0.890477,0.890853
2,Porter,Unigram + Bigram,0.872040,0.872080,0.872040,0.872009
3,Porter,Trigram,0.844300,0.880670,0.844300,0.846203
4,Porter,Bigram + Trigram,0.894198,0.903252,0.894198,0.894663
5,Porter,Unigram + Bigram + Trigram,0.873224,0.873156,0.873224,0.873110
6,Snowball,Unigram,0.786959,0.786796,0.786959,0.786792
7,Snowball,Bigram,0.889800,0.898089,0.889800,0.890165
8,Snowball,Unigram + Bigram,0.872040,0.872090,0.872040,0.871995
9,Snowball,Trigram,0.843961,0.880498,0.843961,0.845861
10,Snowball,Bigram + Trigram,0.894537,0.903532,0.894537,0.895000
11,Snowball,Unigram + Bigram + Trigram,0.872040,0.871952,0.872040,0.871917
12,Lemmatization,Unigram,0.800660,0.800409,0.800660,0.800468
13,Lemmatization,Bigram,0.889039,0.897830,0.889039,0.889463
14,Lemmatization,Unigram + Bigram,0.872717,0.872716,0.872717,0.872664
15,Lemmatization,Trigram,0.839394,0.877658,0.839394,0.841296
16,Lemmatization,Bigram + Trigram,0.892422,0.901609,0.892422,0.892963
17,Lemmatization,Unigram + Bigram + Trigram,0.875761,0.875703,0.875761,0.875662

In [52]:
results_df.sort_values(
    by="Accuracy",
    ascending=False
)

,Preprocessing,N-gram,Accuracy,Precision,Recall,F1-Score
10,Snowball,Bigram + Trigram,0.894537,0.903532,0.894537,0.895000
4,Porter,Bigram + Trigram,0.894198,0.903252,0.894198,0.894663
16,Lemmatization,Bigram + Trigram,0.892422,0.901609,0.892422,0.892963
1,Porter,Bigram,0.890477,0.898818,0.890477,0.890853
7,Snowball,Bigram,0.889800,0.898089,0.889800,0.890165
13,Lemmatization,Bigram,0.889039,0.897830,0.889039,0.889463
17,Lemmatization,Unigram + Bigram + Trigram,0.875761,0.875703,0.875761,0.875662
5,Porter,Unigram + Bigram + Trigram,0.873224,0.873156,0.873224,0.873110
14,Lemmatization,Unigram + Bigram,0.872717,0.872716,0.872717,0.872664
2,Porter,Unigram + Bigram,0.872040,0.872080,0.872040,0.872009
8,Snowball,Unigram + Bigram,0.872040,0.872090,0.872040,0.871995
11,Snowball,Unigram + Bigram + Trigram,0.872040,0.871952,0.872040,0.871917
3,Porter,Trigram,0.844300,0.880670,0.844300,0.846203
9,Snowball,Trigram,0.843961,0.880498,0.843961,0.845861
15,Lemmatization,Trigram,0.839394,0.877658,0.839394,0.841296
12,Lemmatization,Unigram,0.800660,0.800409,0.800660,0.800468
6,Snowball,Unigram,0.786959,0.786796,0.786959,0.786792
0,Porter,Unigram,0.786367,0.786234,0.786367,0.786230

In [53]:
best_result = results_df.loc[
    results_df["Accuracy"].idxmax()
]

print(best_result)

Preprocessing            Snowball
N-gram           Bigram + Trigram
Accuracy                 0.894537
Precision                0.903532
Recall                   0.894537
F1-Score                    0.895
Name: 10, dtype: object

In [54]:
results_df[
    ["Preprocessing", "N-gram", "Accuracy"]
].sort_values(
    by="Accuracy",
    ascending=False
)

    Preprocessing                      N-gram  Accuracy
10       Snowball            Bigram + Trigram  0.894537
4          Porter            Bigram + Trigram  0.894198
16  Lemmatization            Bigram + Trigram  0.892422
1          Porter                      Bigram  0.890477
7        Snowball                      Bigram  0.889800
13  Lemmatization                      Bigram  0.889039
17  Lemmatization  Unigram + Bigram + Trigram  0.875761
5          Porter  Unigram + Bigram + Trigram  0.873224
14  Lemmatization            Unigram + Bigram  0.872717
2          Porter            Unigram + Bigram  0.872040
8        Snowball            Unigram + Bigram  0.872040
11       Snowball  Unigram + Bigram + Trigram  0.872040
3          Porter                     Trigram  0.844300
9        Snowball                     Trigram  0.843961
15  Lemmatization                     Trigram  0.839394
12  Lemmatization                     Unigram  0.800660
6        Snowball                     Unigram  0.786959
0          Porter                     Unigram  0.786367

**EXPERIMENT WHICH PREPROCESSING TO USE with BAG OF WORDS**

In [55]:
from sklearn.feature_extraction.text import CountVectorizer

In [56]:
ngram_options = {
    "Unigram": (1, 1),
    "Bigram": (2, 2),
    "Unigram + Bigram": (1, 2),
    "Trigram": (3, 3),
    "Bigram + Trigram": (2, 3),
    "Unigram + Bigram + Trigram": (1, 3)
}

In [57]:
preprocessing_options = {
    "Porter": (porter_train, porter_test),
    "Snowball": (snowball_train, snowball_test),
    "Lemmatization": (lemmatized_train, lemmatized_test)
}

In [58]:
bow_results = []

In [59]:
for preprocessing_name, (train_text, test_text) in preprocessing_options.items():

    for ngram_name, ngram_range in ngram_options.items():

        # Bag of Words
        vectorizer = CountVectorizer(
            ngram_range=ngram_range
        )

        X_train_bow = vectorizer.fit_transform(train_text)
        X_test_bow = vectorizer.transform(test_text)

        # Logistic Regression
        model = LogisticRegression(max_iter=1000)

        model.fit(
            X_train_bow,
            y.loc[X_train]
        )

        # Prediction
        y_pred = model.predict(X_test_bow)

        # Evaluation
        accuracy = accuracy_score(
            y.loc[X_test],
            y_pred
        )

        precision = precision_score(
            y.loc[X_test],
            y_pred,
            average="weighted"
        )

        recall = recall_score(
            y.loc[X_test],
            y_pred,
            average="weighted"
        )

        f1 = f1_score(
            y.loc[X_test],
            y_pred,
            average="weighted"
        )

        # Store results
        bow_results.append({
            "Preprocessing": preprocessing_name,
            "N-gram": ngram_name,
            "Accuracy": accuracy,
            "Precision": precision,
            "Recall": recall,
            "F1-Score": f1
        })

In [60]:
bow_results_df = pd.DataFrame(bow_results)
bow_results_df

,Preprocessing,N-gram,Accuracy,Precision,Recall,F1-Score
0,Porter,Unigram,0.821296,0.822016,0.821296,0.820673
1,Porter,Bigram,0.898512,0.908783,0.898512,0.899546
2,Porter,Unigram + Bigram,0.903924,0.905323,0.903924,0.903882
3,Porter,Trigram,0.841424,0.883787,0.841424,0.845055
4,Porter,Bigram + Trigram,0.897497,0.908925,0.897497,0.898630
5,Porter,Unigram + Bigram + Trigram,0.898173,0.899578,0.898173,0.898051
6,Snowball,Unigram,0.819266,0.820035,0.819266,0.818598
7,Snowball,Bigram,0.898850,0.909096,0.898850,0.899889
8,Snowball,Unigram + Bigram,0.903078,0.904411,0.903078,0.903041
9,Snowball,Trigram,0.841171,0.883739,0.841171,0.844807
10,Snowball,Bigram + Trigram,0.897835,0.909250,0.897835,0.898961
11,Snowball,Unigram + Bigram + Trigram,0.898765,0.900194,0.898765,0.898634
12,Lemmatization,Unigram,0.835081,0.836170,0.835081,0.834542
13,Lemmatization,Bigram,0.897581,0.908223,0.897581,0.898656
14,Lemmatization,Unigram + Bigram,0.903924,0.905406,0.903924,0.903884
15,Lemmatization,Trigram,0.836773,0.881641,0.836773,0.840534
16,Lemmatization,Bigram + Trigram,0.895044,0.907423,0.895044,0.896230
17,Lemmatization,Unigram + Bigram + Trigram,0.897581,0.899289,0.897581,0.897501

In [61]:
bow_results_df.sort_values(
    by="Accuracy",
    ascending=False
)

,Preprocessing,N-gram,Accuracy,Precision,Recall,F1-Score
14,Lemmatization,Unigram + Bigram,0.903924,0.905406,0.903924,0.903884
2,Porter,Unigram + Bigram,0.903924,0.905323,0.903924,0.903882
8,Snowball,Unigram + Bigram,0.903078,0.904411,0.903078,0.903041
7,Snowball,Bigram,0.898850,0.909096,0.898850,0.899889
11,Snowball,Unigram + Bigram + Trigram,0.898765,0.900194,0.898765,0.898634
1,Porter,Bigram,0.898512,0.908783,0.898512,0.899546
5,Porter,Unigram + Bigram + Trigram,0.898173,0.899578,0.898173,0.898051
10,Snowball,Bigram + Trigram,0.897835,0.909250,0.897835,0.898961
17,Lemmatization,Unigram + Bigram + Trigram,0.897581,0.899289,0.897581,0.897501
13,Lemmatization,Bigram,0.897581,0.908223,0.897581,0.898656
4,Porter,Bigram + Trigram,0.897497,0.908925,0.897497,0.898630
16,Lemmatization,Bigram + Trigram,0.895044,0.907423,0.895044,0.896230
3,Porter,Trigram,0.841424,0.883787,0.841424,0.845055
9,Snowball,Trigram,0.841171,0.883739,0.841171,0.844807
15,Lemmatization,Trigram,0.836773,0.881641,0.836773,0.840534
12,Lemmatization,Unigram,0.835081,0.836170,0.835081,0.834542
0,Porter,Unigram,0.821296,0.822016,0.821296,0.820673
6,Snowball,Unigram,0.819266,0.820035,0.819266,0.818598

In [70]:
best_bow_result = (
    bow_results_df
    .sort_values(
        by=["Accuracy", "F1-Score"],
        ascending=False
    )
    .iloc[0]
)

print(best_bow_result)

Preprocessing       Lemmatization
N-gram           Unigram + Bigram
Accuracy                 0.903924
Precision                0.905406
Recall                   0.903924
F1-Score                 0.903884
Name: 14, dtype: object

In [76]:
best_tfidf = results_df.loc[
    results_df["Accuracy"].idxmax()
]

best_bow = (
    bow_results_df
    .sort_values(by=["Accuracy", "F1-Score"], ascending=False)
    .iloc[0]
)

In [77]:
# Create comparison table

comparison_df = pd.DataFrame([
    {
        "Feature Extraction": "TF-IDF",
        "Preprocessing": best_tfidf["Preprocessing"],
        "N-gram": best_tfidf["N-gram"],
        "Accuracy": best_tfidf["Accuracy"],
        "Precision": best_tfidf["Precision"],
        "Recall": best_tfidf["Recall"],
        "F1-Score": best_tfidf["F1-Score"]
    },
    {
        "Feature Extraction": "Bag of Words",
        "Preprocessing": best_bow["Preprocessing"],
        "N-gram": best_bow["N-gram"],
        "Accuracy": best_bow["Accuracy"],
        "Precision": best_bow["Precision"],
        "Recall": best_bow["Recall"],
        "F1-Score": best_bow["F1-Score"]
    }
])

print(comparison_df)

  Feature Extraction  Preprocessing            N-gram  Accuracy  Precision  \
0             TF-IDF       Snowball  Bigram + Trigram  0.894537   0.903532
1       Bag of Words  Lemmatization  Unigram + Bigram  0.903924   0.905406

     Recall  F1-Score
0  0.894537  0.895000
1  0.903924  0.903884

In [78]:
comparison_df[
    ["Accuracy", "Precision", "Recall", "F1-Score"]
] = comparison_df[
    ["Accuracy", "Precision", "Recall", "F1-Score"]
] * 100

comparison_df.round(2)

,Feature Extraction,Preprocessing,N-gram,Accuracy,Precision,Recall,F1-Score
0,TF-IDF,Snowball,Bigram + Trigram,89.45,90.35,89.45,89.50
1,Bag of Words,Lemmatization,Unigram + Bigram,90.39,90.54,90.39,90.39

In [79]:
print("Best TF-IDF Configuration:\n")
print(best_tfidf)

print("\nBest Bag of Words Configuration:\n")
print(best_bow)

Best TF-IDF Configuration:

Preprocessing            Snowball
N-gram           Bigram + Trigram
Accuracy                 0.894537
Precision                0.903532
Recall                   0.894537
F1-Score                    0.895
Name: 10, dtype: object

Best Bag of Words Configuration:

Preprocessing       Lemmatization
N-gram           Unigram + Bigram
Accuracy                 0.903924
Precision                0.905406
Recall                   0.903924
F1-Score                 0.903884
Name: 14, dtype: object

In [80]:
df.columns

Index(['USER_ID', 'ENTITY', 'SENTIMENT', 'TEXT', 'CLEAN_TEXT', 'TOKENS',
       'NO_STOPWORDS', 'PORTER_STEMMED', 'SNOWBALL_STEMMED', 'PORTER_TEXT',
       'SNOWBALL_TEXT', 'LEMMATIZED', 'BIGRAMS', 'LEMMATIZED_TEXT'],
      dtype='str')

In [68]:
comparison_df.to_csv("Feature_Extraction_Comparison.csv", index=False)